<?php

namespace Database\Seeders;

use App\Models\Parameter\Language;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Language::create(['name' => 'Akan']);
        Language::create(['name' => 'Albanian']);
        Language::create(['name' => 'Amharic']);
        Language::create(['name' => 'Arabic']);
        Language::create(['name' => 'Arabic, Algerian']);
        Language::create(['name' => 'Arabic, Mesopotamian']);
        Language::create(['name' => 'Arabic, Moroccan']);
        Language::create(['name' => 'Arabic, Najdi Spoken']);
        Language::create(['name' => 'Arabic, North Levantine']);
        Language::create(['name' => 'Arabic, Saidi']);
        Language::create(['name' => 'Arabic, Sanaani']);
        Language::create(['name' => 'Arabic, Sudanese']);
        Language::create(['name' => 'Arabic, Tunisian']);
        Language::create(['name' => 'Armenian']);
        Language::create(['name' => 'Assamese']);
        Language::create(['name' => 'Awadhi']);
        Language::create(['name' => 'Aymara']);
        Language::create(['name' => 'Azerbaijani, North']);
        Language::create(['name' => 'Azerbaijani, South']);
        Language::create(['name' => 'Belarusan']);
        Language::create(['name' => 'Bengali']);
        Language::create(['name' => 'Bhojpuri']);
        Language::create(['name' => 'Bislama']);
        Language::create(['name' => 'Bokmal Norwegian']);
        Language::create(['name' => 'Bosnian']);
        Language::create(['name' => 'Bulgarian']);
        Language::create(['name' => 'Burmese']);
        Language::create(['name' => 'Cantonese']);
        Language::create(['name' => 'Catalan']);
        Language::create(['name' => 'Cebuano']);
        Language::create(['name' => 'Chhattisgarhi']);
        Language::create(['name' => 'Chinese, Gan']);
        Language::create(['name' => 'Chinese, Hakka']);
        Language::create(['name' => 'Chinese, Jinyu']);
        Language::create(['name' => 'Chinese, Mandarin']);
        Language::create(['name' => 'Chinese, Min Bei']);
        Language::create(['name' => 'Chinese, Min Nan']);
        Language::create(['name' => 'Chinese, Wu']);
        Language::create(['name' => 'Chinese, Xiang']);
        Language::create(['name' => 'Chinese, Yue']);
        Language::create(['name' => 'Chittagonian']);
        Language::create(['name' => 'Crioulo']);
        Language::create(['name' => 'Croatian']);
        Language::create(['name' => 'Czech']);
        Language::create(['name' => 'Danish']);
        Language::create(['name' => 'Deccan']);
        Language::create(['name' => 'Dhivehi']);
        Language::create(['name' => 'Dutch']);
        Language::create(['name' => 'Dzongkha']);
        Language::create(['name' => 'English (AU)']);
        Language::create(['name' => 'English(UK)']);
        Language::create(['name' => 'English(US)']);
        Language::create(['name' => 'Estonian']);
        Language::create(['name' => 'Farsi, Eastern']);
        Language::create(['name' => 'Farsi, Western']);
        Language::create(['name' => 'Fijian']);
        Language::create(['name' => 'Finnish']);
        Language::create(['name' => 'French']);
        Language::create(['name' => 'Fulfulde, Nigerian']);
        Language::create(['name' => 'Georgian']);
        Language::create(['name' => 'German']);
        Language::create(['name' => 'Greek']);
        Language::create(['name' => 'Guarani']);
        Language::create(['name' => 'Gujarati']);
        Language::create(['name' => 'Haitian Creole French']);
        Language::create(['name' => 'Haryanvi']);
        Language::create(['name' => 'Hausa']);
        Language::create(['name' => 'Hebrew']);
        Language::create(['name' => 'Hiligaynon']);
        Language::create(['name' => 'Hindi']);
        Language::create(['name' => 'Hiri Motu']);
        Language::create(['name' => 'Hokkien']);
        Language::create(['name' => 'Hungarian']);
        Language::create(['name' => 'Icelandic']);
        Language::create(['name' => 'Igbo']);
        Language::create(['name' => 'Ilocano']);
        Language::create(['name' => 'Indonesian']);
        Language::create(['name' => 'Italian']);
        Language::create(['name' => 'Japanese']);
        Language::create(['name' => 'Javanese']);
        Language::create(['name' => 'Kannada']);
        Language::create(['name' => 'Kazakh']);
        Language::create(['name' => 'Khmer, Central']);
        Language::create(['name' => 'Kirundi']);
        Language::create(['name' => 'Kiswahili']);
        Language::create(['name' => 'Korean']);
        Language::create(['name' => 'Kurmanji']);
        Language::create(['name' => 'Kyrgyz']);
        Language::create(['name' => 'Lao']);
        Language::create(['name' => 'Latvian']);
        Language::create(['name' => 'Lithuanian']);
        Language::create(['name' => 'Lombard']);
        Language::create(['name' => 'Luxembourgish']);
        Language::create(['name' => 'Macedonian']);
        Language::create(['name' => 'Madura']);
        Language::create(['name' => 'Magahi']);
        Language::create(['name' => 'Maithili']);
        Language::create(['name' => 'Malagasy']);
        Language::create(['name' => 'Malay']);
        Language::create(['name' => 'Malayalam']);
        Language::create(['name' => 'Maltese']);
        Language::create(['name' => 'Maori']);
        Language::create(['name' => 'Marathi']);
        Language::create(['name' => 'Marshallese']);
        Language::create(['name' => 'Marwari']);
        Language::create(['name' => 'Moldovan']);
        Language::create(['name' => 'Mongolian']);
        Language::create(['name' => 'Montenegrin']);
        Language::create(['name' => 'Napoletano-Calabrese']);
        Language::create(['name' => 'Nauruan']);
        Language::create(['name' => 'Nepali']);
        Language::create(['name' => 'Nynorsk Norwegian']);
        Language::create(['name' => 'Oriya']);
        Language::create(['name' => 'Oromo, West-Central']);
        Language::create(['name' => 'Palauan']);
        Language::create(['name' => 'Panjabi, Eastern']);
        Language::create(['name' => 'Panjabi, Western']);
        Language::create(['name' => 'Pashto, Northern']);
        Language::create(['name' => 'Pashto, Southern']);
        Language::create(['name' => 'Polish']);
        Language::create(['name' => 'Portuguese']);
        Language::create(['name' => 'Quechua']);
        Language::create(['name' => 'Romanian']);
        Language::create(['name' => 'Russian']);
        Language::create(['name' => 'Rwanda']);
        Language::create(['name' => 'Saraiki']);
        Language::create(['name' => 'Serbian']);
        Language::create(['name' => 'Serbo-Croatian']);
        Language::create(['name' => 'Sesotho']);
        Language::create(['name' => 'Seychellois Creole']);
        Language::create(['name' => 'Shona']);
        Language::create(['name' => 'Sindhi']);
        Language::create(['name' => 'Sinhala']);
        Language::create(['name' => 'siSwati']);
        Language::create(['name' => 'Slovak']);
        Language::create(['name' => 'Slovene']);
        Language::create(['name' => 'Somali']);
        Language::create(['name' => 'Spanish']);
        Language::create(['name' => 'Sunda']);
        Language::create(['name' => 'Swahili']);
        Language::create(['name' => 'Swedish']);
        Language::create(['name' => 'Tagalog']);
        Language::create(['name' => 'Tajik']);
        Language::create(['name' => 'Tamil']);
        Language::create(['name' => 'Tatar']);
        Language::create(['name' => 'Telugu']);
        Language::create(['name' => 'Teochew']);
        Language::create(['name' => 'Thai']);
        Language::create(['name' => 'Thai, Northeastern']);
        Language::create(['name' => 'Tigrinya']);
        Language::create(['name' => 'Tok Pisin']);
        Language::create(['name' => 'Turkish']);
        Language::create(['name' => 'Turkmen']);
        Language::create(['name' => 'Ukrainian']);
        Language::create(['name' => 'Urdu']);
        Language::create(['name' => 'Uyghur']);
        Language::create(['name' => 'Uzbek, Northern']);
        Language::create(['name' => 'Vietnamese']);
        Language::create(['name' => 'Yoruba']);
        Language::create(['name' => 'Zhuang, Northern']);
        Language::create(['name' => 'Zulu']);
    }
}
